### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by littlepeace2005** [Aurorum-Studio/flarum-app#7]
One is not able to upload local files through fof-upload.

**Comment by Aurorum-Studio** [comment]
Hi, sorry to reply you late, I'm quite busy these days, this is because upload in an Android app need to use an upload API, which is not in the webview structure, I have listed this in my todo list, I think I'll add this function before June. Thank you for give me this feedback, and thank you for using this project.

**Comment by LiteCat0905** [comment]
请问目前是已经支持上传了吗？
